version: '2'
services:
  web:
    image: kibana
    ports:
     - "5601:5601"
    links: 
      - redis
      - logstash
      - elasticsearch
    depends_on:
      - redis
      - logstash
      - elasticsearch
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
  redis:
    image: redis
  logstash:
    image: "logstash:2.3.2-1"
    volumes:
      - logstash:/etc/logstash/conf.d
  elasticsearch:
    image: elasticsearch
    volumes:
      - ./elasticsearch:/etc/elasticsearch/utils
volumes:
  logstash:
    external: false
