version: '2'
services:
  web:
    image: kibana
    ports:
      - "5601:5601"
    links: 
      - redis
      - logstash
      - elasticsearch
    depends_on:
      - redis
      - logstash
      - elasticsearch
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
  redis:
    image: redis
    ports:
      - "6379:6379" 
  logstash:
    image: "logstash:2.3.2-1"
    volumes:
      - ./logstash:/etc/logstash/conf.d
    command: logstash -f /etc/logstash/conf.d/central.conf
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200" 
      - "9300:9300" 
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      - /usr/share/elasticsearch/backups:/usr/share/elasticsearch/backups
      
volumes:
  logstash:
    external: false
