#!/bin/bash
#git clone https://gist.github.com/0e0d9733c4243941f4e8.git ls-es-template

max_tries=25
while [[ $(curl -X HEAD -s -D - 127.0.0.1:9200 | grep 'HTTP') != *200* ]]
do
  if [ $max_tries = 0 ]; then
   echo "FATAL: elasticsearch never booted. Please review config!"
   exit -1
  fi
  echo "Waiting for elasticsearch to boot"
  sleep 1
  max_tries=$(($max_tries - 1))
done

curl -X PUT 127.0.0.1:9200/_template/logstash -d @ls-es-template-20150831.json
